version: "2"
plugins:
  sonar-python:
    enabled: true
    config:
      tests_patterns:
        - tests/**
        - docs/**
        - sphinx-docs/**
exclude_patterns:
  - tests/
  - docs/
  - sphinx-docs/
