env:
  global:
    - CC_TEST_REPORTER_ID=3e113735ca4277f3ea59db80fbdca7bceb293775290baa2db1fdc216ba940228
language:
  - python
matrix:
  include:
  - python: "3.6"
    env:
      SPHINX_TARGET: "yes"
      TEST_REPORT_TARGET: "yes"
  - python: "3.7-dev"
install:
  - pip install pipenv
  - make build
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  - make test
  - '[ $TEST_REPORT_TARGET ] && ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT || echo "Skip send test report"'
  - '[ $SPHINX_TARGET ] && (make doctest) || echo "Skip doctest"'
notifications:
  slack:
    secure: S81vdt0O2Tyb5XD/wyTysjxzsh8eRBu55KF2n/zjScWxh78pVKUicfJd2CzrdsQ9EVdugY/E2PCyLDaX9jWRIyY0JiQ2e6Q62wcgAnZuTPIwPTcVBljd9I1ptuKKq5EWeeQKr2lnxA+EKUfjKZsflEMOKRmbQnVrJDOLADT7JoycuMn17mzobz9gu7hC9Haac+WUJxElhFZt/TpADEBVcn8bngMr3lg4eKgrodRvGi2BZCeTSCoq43O/HUaJ9o9URf/ifzvtrc2DJr1PSy3NRk5gMt++YpHTDDS2+zNzXgM1Ve0KvvrsdB3VRDx2ICWD5PV6oZmT9xcaKOKG5+VSAml9BMp2e4I0PQxkoaGCyi3bLhqLW/UQPcj2UIhIbRN8tTF0lMRMT7RbExjfD7MBcR4wRwIbWSZuVnJxLE50HFOkn+aZ2ZIJMObJbnkxwCoFz3Eikn0B/TkkvlVswvNQpitjwBBGVMiSUSHYcChsKf/mm7zmjzQgRoRzag+5XfACEm347PEyGooSt6g7Fehvtw/Zz2HeJwz5pCu/SUrdLexOPydwNQrX40yIYhD/PvA/pLnyrlOVa6W/1JBlOYuxfno1wWpLyxVoW0n+oRgKmMdMxAuteFiyeHEW1tLz8KUDbW64cEfQorvdtMYxKKY5ieGFppvA/R0XnifvveM7S9Y=
