name: "Tests"

on:
    push:
        paths:
            - ".github/**/*"
            - "owlmixin/*"
            - "owlmixin/**/*"
            - "tests/*"
            - "tests/**/*"
            - "Pipfile.lock"
    schedule:
        - cron: "0 0 * * *"

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python: ["3.6", "3.7"]
        name: Python ${{ matrix.python }}

        steps:
            - name: Checkout a repository
              uses: actions/checkout@v1

            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.python }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip pipenv
                  sed -ri 's/python_version = ".+"/python_version = "${{ matrix.python }}"/g' Pipfile
                  pipenv install --dev --skip-lock

            - name: Doc test
              run: make doctest

            - name: Unit test
              id: unittest
              run: make test
            - name: Test report
              if: matrix.python == 3.7 && success()
              env:
                  CC_TEST_REPORTER_ID: 3e113735ca4277f3ea59db80fbdca7bceb293775290baa2db1fdc216ba940228
              run: |
                  curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                  chmod +x ./cc-test-reporter
                  ./cc-test-reporter after-build

            - name: Slack notification
              uses: homoluctus/slatify@master
              if: always()
              with:
                  type: ${{ job.status }}
                  job_name: ":python:*${{ matrix.python }}* Tests ${{ success() || @channel }}"
                  icon_emoji: "tio2"
                  url: ${{ secrets.SLACK_WEBHOOK }}
