name: "Tests"

on:
    push:
        paths:
            - ".github/**/*"
            - "owlmixin/*"
            - "owlmixin/**/*"
            - "tests/*"
            - "tests/**/*"
            - "Pipfile.lock"
    schedule:
        - cron: "0 0 * * *"

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python: ["3.6", "3.7", "3.8"]
        name: Python ${{ matrix.python }}

        steps:
            - name: Checkout a repository
              uses: actions/checkout@v1
            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.python }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip pipfile-requirements
                  pipfile2req > requirements.txt
                  pip install -r requirements.txt
                  pip install pytest pytest-cov mock
            - name: Test documentation
              run: python -m doctest owlmixin/{__init__.py,transformers.py,owlcollections.py,owlenum.py,owloption.py,util.py} -v
            - name: Unit test
              run: python -m pytest -vv --cov-report=xml --cov=. tests/
            - name: Slack notification
              uses: homoluctus/slatify@master
              if: always()
              with:
                  type: ${{ job.status }}
                  job_name: ":python:*${{ matrix.python }}* Tests"
                  icon_emoji: "tio2"
                  url: ${{ secrets.SLACK_WEBHOOK }}
